title: 数字攻略
author: 吾儿滨滨
menus: 
  主页: /
  归档: /archives
  关于我: /about
links:
  GitHub: https://github.com/junbin123
  微博: https://weibo.com/u/6208092799
  公众号: https://docs.qq.com/doc/DVlVBZGF3RVpMVWVW
  微信: https://docs.qq.com/doc/DVkZkdllJU3FUTmZC

# 设置代码高亮样式，例如：atom-one-dark、gruvbox-dark
# https://highlightjs.org/static/demo/
code_style: gruvbox-dark

favicon:
  medium: /images/favicon.ico